[changelog]
header = """# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).\n
"""
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [Unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {{ commit.message | split(pat="\n") | first | upper_first }}\
          {% if commit.github.pr_number %} \
            ([#{{ commit.github.pr_number }}]({{ commit.github.pr_url }}))\
          {% endif %}
    {% endfor %}
{% endfor %}\n
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
protect_breaking_commits = true
filter_commits = false
tag_pattern = "v[0-9].*"
sort_commits = "oldest"

# keepachangelog.com standard categories: Added, Changed, Deprecated, Removed, Fixed, Security
commit_parsers = [
  { message = "^feat", group = "Added" },
  { message = "^fix", group = "Fixed" },
  { message = "^security", group = "Security" },
  { message = "^deprecate", group = "Deprecated" },
  { message = "^doc", group = "Changed" },
  { message = "^docs", group = "Changed" },
  { message = "^perf", group = "Changed" },
  { message = "^refactor", group = "Changed" },
  { message = "^style", group = "Changed" },
  { message = "^test", skip = true },
  { message = "^chore\\(release\\)", skip = true },
  { message = "^chore", group = "Changed" },
  { message = "^ci", skip = true },
  { message = "^build", skip = true },
  { body = ".*security", group = "Security" },
  { message = "^revert", group = "Changed" },
]
